export const categories = [
  { slug: "leuchtmittel", label: "Leuchtmittel", enabled: true },
  { slug: "schalter", label: "Schalter", enabled: false },
  { slug: "hubs", label: "Hubs", enabled: false },
];

export const products = [
  {
    id: "white-e14-candle-470",
    slug: "philips-hue-white-e14-kerze-470",
    title: "Philips Hue White E14 Kerze 470",
    categorySlug: "leuchtmittel",
    category: "Leuchtmittel",
    line: "White",
    spec: "E14 · 470 lm",
    compatibility: ["Bluetooth", "Alexa", "Google Home"],
    short: "Warmes Licht fuer Tisch- und Fensterleuchten.",
    description: "Kompaktes E14-Leuchtmittel fuer kleinere Leuchten. Warmweiss, schnell eingerichtet und ideal fuer ruhige Alltagsbeleuchtung.",
    priceCents: 1699,
    stockLabel: "Auf Lager",
    image: "/assets/products/philips-hue-white-e14-candle-470.png",
    gallery: ["/assets/products/philips-hue-white-e14-candle-470.png"],
  },
  {
    id: "white-color-e14-candle-470",
    slug: "philips-hue-white-color-e14-kerze-470",
    title: "Philips Hue White & Color E14 Kerze 470",
    categorySlug: "leuchtmittel",
    category: "Leuchtmittel",
    line: "White & Color",
    spec: "E14 · 470 lm",
    compatibility: ["Bluetooth", "Alexa", "Google Home"],
    short: "Farbiges Licht fuer kleinere Leuchten und Akzente.",
    description: "E14-Kerze mit warmem Weiss, kuehlem Weiss und Farblicht. Gut fuer Akzente, Routinen und kleine Wohnbereiche.",
    priceCents: 2999,
    stockLabel: "Auf Lager",
    image: "/assets/products/philips-hue-white-color-e14-candle-470.png",
    gallery: ["/assets/products/philips-hue-white-color-e14-candle-470.png"],
  },
  {
    id: "white-e27-thin-filament-580",
    slug: "philips-hue-white-e27-thin-filament-580",
    title: "Philips Hue White E27 Filament 580",
    categorySlug: "leuchtmittel",
    category: "Leuchtmittel",
    line: "Filament",
    spec: "E27 · 580 lm",
    compatibility: ["Bluetooth", "Alexa", "Google Home"],
    short: "Dekoratives Filament fuer offene Fassungen.",
    description: "Schlanke Filamentlampe fuer sichtbare Leuchten, Sideboards und offene Pendel. Warmes Licht mit dekorativer Optik.",
    priceCents: 2299,
    stockLabel: "Auf Lager",
    image: "/assets/products/philips-hue-white-e27-thin-filament-580.png",
    gallery: ["/assets/products/philips-hue-white-e27-thin-filament-580.png"],
  },
  {
    id: "white-ambiance-e27-1100",
    slug: "philips-hue-white-ambiance-e27-1100",
    title: "Philips Hue White Ambiance E27 1100",
    categorySlug: "leuchtmittel",
    category: "Leuchtmittel",
    line: "White Ambiance",
    spec: "E27 · 1100 lm",
    compatibility: ["Matter", "Apple Home", "Google Home"],
    short: "Variables Weisslicht fuer Alltag und Abend.",
    description: "Helles White-Ambiance-Leuchtmittel fuer Wohnraum, Essbereich und Home-Office. Warm bis kuehlweiss, klar und vielseitig.",
    priceCents: 2499,
    stockLabel: "Auf Lager",
    image: "/assets/products/philips-hue-white-ambiance-e27-1100.png",
    gallery: ["/assets/products/philips-hue-white-ambiance-e27-1100.png"],
  },
  {
    id: "white-e14-filament-candle-300",
    slug: "philips-hue-white-e14-filament-kerze-300",
    title: "Philips Hue White Filament E14 Kerze 300",
    categorySlug: "leuchtmittel",
    category: "Leuchtmittel",
    line: "Filament",
    spec: "E14 · 300 lm",
    compatibility: ["Bluetooth", "Alexa", "Google Home"],
    short: "Feine Filament-Kerze fuer kleinere Leuchten.",
    description: "Dekorative Filament-Kerze fuer offene Wand- und Tischleuchten. Ruhiges Lichtbild und bewusst reduzierte Optik.",
    priceCents: 1999,
    stockLabel: "Auf Lager",
    image: "/assets/products/philips-hue-white-e14-filament-candle-300.png",
    gallery: ["/assets/products/philips-hue-white-e14-filament-candle-300.png"],
  },
  {
    id: "white-e27-filament-550",
    slug: "philips-hue-white-e27-filament-550",
    title: "Philips Hue White E27 Filament 550",
    categorySlug: "leuchtmittel",
    category: "Leuchtmittel",
    line: "Filament",
    spec: "E27 · 550 lm",
    compatibility: ["Bluetooth", "Alexa", "Google Home"],
    short: "Warme Filament-Optik fuer sichtbare Wohnraumleuchten.",
    description: "Hue White Filament fuer offene Pendel und Tischleuchten. Warmes Licht, dekorative Form und unkomplizierte Steuerung.",
    priceCents: 2199,
    stockLabel: "Auf Lager",
    image: "/assets/products/philips-hue-white-e27-filament-550.png",
    gallery: ["/assets/products/philips-hue-white-e27-filament-550.png"],
  },
  {
    id: "white-color-e27-1100",
    slug: "philips-hue-white-color-e27-1100",
    title: "Philips Hue White & Color E27 1100",
    categorySlug: "leuchtmittel",
    category: "Leuchtmittel",
    line: "White & Color",
    spec: "E27 · 1100 lm",
    compatibility: ["Matter", "Apple Home", "Google Home"],
    short: "Farblicht fuer Wohnraeume, Szenen und smarte Routinen.",
    description: "Starkes White-and-Color-Leuchtmittel fuer Wohn- und Essbereich. Helles Weisslicht und Farbstimmungen in einer Lampe.",
    priceCents: 4499,
    stockLabel: "Auf Lager",
    image: "/assets/products/philips-hue-white-color-e27-1100.png",
    gallery: ["/assets/products/philips-hue-white-color-e27-1100.png"],
  },
];

export function getProduct(slug) {
  return products.find((product) => product.slug === slug);
}

export function getCategoryProducts(slug) {
  if (slug !== "leuchtmittel") {
    return [];
  }
  return products;
}
