export const seedCategories = [
  { id: "cat-leuchtmittel", slug: "leuchtmittel", label: "Leuchtmittel", enabled: true, position: 0 },
  { id: "cat-schalter", slug: "schalter", label: "Schalter", enabled: true, position: 1 },
  { id: "cat-hubs", slug: "hubs", label: "Hubs", enabled: true, position: 2 },
];

export const seedProducts = [
  {
    id: "white-e14-candle-470",
    slug: "philips-hue-white-e14-kerze-470",
    title: "Philips Hue White E14 Kerze 470",
    categorySlug: "leuchtmittel",
    category: "Leuchtmittel",
    line: "White",
    spec: "E14 · 470 lm",
    compatibility: ["Bluetooth", "Alexa", "Google Home"],
    short: "Warmes Licht für Tisch- und Fensterleuchten.",
    description: "Kompaktes E14-Leuchtmittel für kleinere Leuchten. Warmweiß, schnell eingerichtet und ideal für ruhige Alltagsbeleuchtung.",
    priceCents: 1699,
    stockLabel: "Auf Lager",
    stockCount: 8,
    visible: true,
    image: "/assets/products/philips-hue-white-e14-candle-470.png",
    gallery: ["/assets/products/philips-hue-white-e14-candle-470.png"],
  },
  {
    id: "white-color-e14-candle-470",
    slug: "philips-hue-white-color-e14-kerze-470",
    title: "Philips Hue White & Color E14 Kerze 470",
    categorySlug: "leuchtmittel",
    category: "Leuchtmittel",
    line: "White & Color",
    spec: "E14 · 470 lm",
    compatibility: ["Bluetooth", "Alexa", "Google Home"],
    short: "Farbiges Licht für kleinere Leuchten und Akzente.",
    description: "E14-Kerze mit warmem Weiß, kühlem Weiß und Farblicht. Gut für Akzente, Routinen und kleine Wohnbereiche.",
    priceCents: 2999,
    stockLabel: "Auf Lager",
    stockCount: 6,
    visible: true,
    image: "/assets/products/philips-hue-white-color-e14-candle-470.png",
    gallery: ["/assets/products/philips-hue-white-color-e14-candle-470.png"],
  },
  {
    id: "white-e27-thin-filament-580",
    slug: "philips-hue-white-e27-thin-filament-580",
    title: "Philips Hue White E27 Filament 580",
    categorySlug: "leuchtmittel",
    category: "Leuchtmittel",
    line: "Filament",
    spec: "E27 · 580 lm",
    compatibility: ["Bluetooth", "Alexa", "Google Home"],
    short: "Dekoratives Filament für offene Fassungen.",
    description: "Schlanke Filamentlampe für sichtbare Leuchten, Sideboards und offene Pendel. Warmes Licht mit dekorativer Optik.",
    priceCents: 2299,
    stockLabel: "Auf Lager",
    stockCount: 7,
    visible: true,
    image: "/assets/products/philips-hue-white-e27-thin-filament-580.png",
    gallery: ["/assets/products/philips-hue-white-e27-thin-filament-580.png"],
  },
  {
    id: "white-ambiance-e27-1100",
    slug: "philips-hue-white-ambiance-e27-1100",
    title: "Philips Hue White Ambiance E27 1100",
    categorySlug: "leuchtmittel",
    category: "Leuchtmittel",
    line: "White Ambiance",
    spec: "E27 · 1100 lm",
    compatibility: ["Matter", "Apple Home", "Google Home"],
    short: "Variables Weißlicht für Alltag und Abend.",
    description: "Helles White-Ambiance-Leuchtmittel für Wohnraum, Essbereich und Home-Office. Warm bis kühlweiß, klar und vielseitig.",
    priceCents: 2499,
    stockLabel: "Auf Lager",
    stockCount: 10,
    visible: true,
    image: "/assets/products/philips-hue-white-ambiance-e27-1100.png",
    gallery: ["/assets/products/philips-hue-white-ambiance-e27-1100.png"],
  },
  {
    id: "white-e14-filament-candle-300",
    slug: "philips-hue-white-e14-filament-kerze-300",
    title: "Philips Hue White Filament E14 Kerze 300",
    categorySlug: "leuchtmittel",
    category: "Leuchtmittel",
    line: "Filament",
    spec: "E14 · 300 lm",
    compatibility: ["Bluetooth", "Alexa", "Google Home"],
    short: "Feine Filament-Kerze für kleinere Leuchten.",
    description: "Dekorative Filament-Kerze für offene Wand- und Tischleuchten. Ruhiges Lichtbild und bewusst reduzierte Optik.",
    priceCents: 1999,
    stockLabel: "Auf Lager",
    stockCount: 5,
    visible: true,
    image: "/assets/products/philips-hue-white-e14-filament-candle-300.png",
    gallery: ["/assets/products/philips-hue-white-e14-filament-candle-300.png"],
  },
  {
    id: "white-e27-filament-550",
    slug: "philips-hue-white-e27-filament-550",
    title: "Philips Hue White E27 Filament 550",
    categorySlug: "leuchtmittel",
    category: "Leuchtmittel",
    line: "Filament",
    spec: "E27 · 550 lm",
    compatibility: ["Bluetooth", "Alexa", "Google Home"],
    short: "Warme Filament-Optik für sichtbare Wohnraumleuchten.",
    description: "Hue White Filament für offene Pendel und Tischleuchten. Warmes Licht, dekorative Form und unkomplizierte Steuerung.",
    priceCents: 2199,
    stockLabel: "Auf Lager",
    stockCount: 9,
    visible: true,
    image: "/assets/products/philips-hue-white-e27-filament-550.png",
    gallery: ["/assets/products/philips-hue-white-e27-filament-550.png"],
  },
  {
    id: "white-color-e27-1100",
    slug: "philips-hue-white-color-e27-1100",
    title: "Philips Hue White & Color E27 1100",
    categorySlug: "leuchtmittel",
    category: "Leuchtmittel",
    line: "White & Color",
    spec: "E27 · 1100 lm",
    compatibility: ["Matter", "Apple Home", "Google Home"],
    short: "Farblicht für Wohnräume, Szenen und smarte Routinen.",
    description: "Starkes White-and-Color-Leuchtmittel für Wohn- und Essbereich. Helles Weißlicht und Farbstimmungen in einer Lampe.",
    priceCents: 4499,
    stockLabel: "Auf Lager",
    stockCount: 4,
    visible: true,
    image: "/assets/products/philips-hue-white-color-e27-1100.png",
    gallery: ["/assets/products/philips-hue-white-color-e27-1100.png"],
  },
];
